# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-ast
      - id: check-toml

    # Ensure pyproject.toml is valid
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.19
    hooks:
      - id: validate-pyproject

    # Ensure there are no `eval` or `warn` calls in the code
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn

    # Check documentation is in place
    # Minimum percentage defined in pyproject.toml
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0 # or master if you're bold
    hooks:
      - id: interrogate

    # Check for common spelling errors
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

    # Check the code could user newer constructs per the stated version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py312]

    # Use ruff for formatting and linting
    # What is done is defined in pyproject.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

    # Check markdown files are properly linted
    # Settings in pyproject.toml
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.23
    hooks:
      - id: pymarkdown
